project:
  namespace: "org.simplemodeling.textus"
  id: "Experiment"
  name: "textus-experiment"
  title: "Textus Experiment"
  kind: car
  scalaPackage: "org.simplemodeling.textus.experiment"
  component:
    name: "Experiment"
    className: "ExperimentComponent"
    displayName: "Textus Experiment"
    version: "0.1.1-SNAPSHOT"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.4-SNAPSHOT"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.2-SNAPSHOT"
    test:
      - "org.scalatest::scalatest:3.2.19"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    abi:
      dependencies: []
    manifest_metadata:
      boundedContext: "experiment"
      domain: "experiment-management"
    runtime:
      cncf:
        minimum: "0.5.2-SNAPSHOT"
        excluded: []
        tested:
          - "0.5.2-SNAPSHOT"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-experiment"
