project:
  name: "textus-experiment"
  title: "Textus Experiment"
  kind: car
  organization: "org.textus"
  scalaPackage: "org.simplemodeling.textus.experiment"
  component:
    name: "textus-experiment"
    className: "Experiment"
    displayName: "Textus Experiment"
    version: "0.1.0"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.0"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.1"
    test:
      - "org.scalatest::scalatest:3.2.19"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    abi:
      dependencies: []
    manifest_metadata:
      boundedContext: "experiment"
      domain: "experiment-management"
    runtime:
      cncf:
        minimum: "0.5.1"
        excluded: []
        tested:
          - "0.5.1"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-experiment"
